config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  root to: "home#index"
  get "home/index"
  get "home/about"
  resources :centros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/centro.rb
class Centro < ApplicationRecord
  validates :clave, presence: { message: "no puede ser vacía"}
  validates :clave, length: { maximum: 10}
  validates :nombre, presence: { message: "no puede ser vacía"}
end

app/models/departamento.rb
class Departamento < ApplicationRecord
  validates :clave, length: { is:10, message: "Solo se pueden escribir claves de 10 caracteres"}
  validates :nombre, length: { maximum: 40, message: "Solo se pueden escribir máximo 40 caracteres"}
  validates :nivel, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10, message: "El valor debe ser un número entre 1 y 10" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/centros_controller.rb
class CentrosController < ApplicationController
  before_action :set_centro, only: %i[ show edit update destroy ]

  # GET /centros or /centros.json
  def index
    @centros = Centro.all
  end

  # GET /centros/1 or /centros/1.json
  def show
  end

  # GET /centros/new
  def new
    @centro = Centro.new
  end

  # GET /centros/1/edit
  def edit
  end

  # POST /centros or /centros.json
  def create
    @centro = Centro.new(centro_params)

    respond_to do |format|
      if @centro.save
        format.html { redirect_to centro_url(@centro), notice: "Centro was successfully created." }
        format.json { render :show, status: :created, location: @centro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centros/1 or /centros/1.json
  def update
    respond_to do |format|
      if @centro.update(centro_params)
        format.html { redirect_to centro_url(@centro), notice: "Centro was successfully updated." }
        format.json { render :show, status: :ok, location: @centro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centros/1 or /centros/1.json
  def destroy
    @centro.destroy!

    respond_to do |format|
      format.html { redirect_to centros_url, notice: "Centro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centro
      @centro = Centro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def centro_params
      params.require(:centro).permit(:clave, :nombre)
    end
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully created." }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully updated." }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy!

    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: "Departamento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:clave, :nombre, :nivel)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/centros/_centro.html.erb
<div id="<%= dom_id centro %>">
  <p>
    <table class="table">
  <thead>
    <tr>
    <strong>Clave:</strong>
    <%= centro.clave %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= centro.nombre %>
  </p>

</div>

app/views/centros/_form.html.erb
<%= form_with(model: centro) do |form| %>
  <% if centro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(centro.errors.count, "error") %> prohibited this centro from being saved:</h2>

      <ul>
        <% centro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :clave, style: "display: block" %>
    <%= form.text_field :clave %>
  </div>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_area :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/centros/edit.html.erb
<% content_for :title, "Editing centro" %>

<h1>Editing centro</h1>

<%= render "form", centro: @centro %>

<br>

<div>
  <%= link_to "Show this centro", @centro %> |
  <%= link_to "Back to centros", centros_path %>
</div>

app/views/centros/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Centros" %>

<h1>Centros</h1>

<div id="centros">
  <% @centros.each do |centro| %>
    <%= render centro %>
    <p>
      <%= link_to "Show this centro", centro %>
    </p>
  <% end %>
</div>

<%= link_to "New centro", new_centro_path %>

app/views/centros/new.html.erb
<% content_for :title, "New centro" %>

<h1>New centro</h1>

<%= render "form", centro: @centro %>

<br>

<div>
  <%= link_to "Back to centros", centros_path %>
</div>

app/views/centros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @centro %>

<div>
  <%= link_to "Edit this centro", edit_centro_path(@centro) %> |
  <%= link_to "Back to centros", centros_path %>

  <%= button_to "Destroy this centro", @centro, method: :delete %>
</div>

app/views/departamentos/_departamento.html.erb
<div id="<%= dom_id departamento %>">
  <p>
    <strong>Clave:</strong>
    <%= departamento.clave %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= departamento.nombre %>
  </p>

  <p>
    <strong>Nivel:</strong>
    <%= departamento.nivel %>
  </p>

</div>

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :clave, style: "display: block" %>
    <%= form.text_field :clave %>
  </div>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :nivel, style: "display: block" %>
    <%= form.number_field :nivel %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Show this departamento", @departamento %> |
  <%= link_to "Back to departamentos", departamentos_path %>
</div>

app/views/departamentos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departamentos</h1>

<div id="departamentos">
  <% @departamentos.each do |departamento| %>
    <%= render departamento %>
    <p>
      <%= link_to "Show this departamento", departamento %>
    </p>
  <% end %>
</div>

<%= link_to "New departamento", new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Back to departamentos", departamentos_path %>
</div>

app/views/departamentos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @departamento %>

<div>
  <%= link_to "Edit this departamento", edit_departamento_path(@departamento) %> |
  <%= link_to "Back to departamentos", departamentos_path %>

  <%= button_to "Destroy this departamento", @departamento, method: :delete %>
</div>

app/views/home/_encabezado.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Inventario', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Centros', centros_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Acerca de...', home_about_path, class: 'nav-link' %>
        </li>
      </ul>
      <form class="d-flex ms-auto">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Acerca de...</h1>

app/views/home/index.html.erb
<ul>
    <h1>Bienvenidos a la página de inicio</h1>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Inventario" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render 'home/encabezado' %>
    <div class="container">
      <br>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>